{
	"materials": {
		"Fatherlands": {
			"WALL06": {
				"__ref": "content/Art/MaterialLibrary/Generic/Past.matlib",
				"name": "Wall_Bloc"
			},
			"patern_mesh02": {
				"__ref": "content/Art/MaterialLibrary/Generic/Past.matlib",
				"name": "Wall_pattern02_mesh"
			},
			"parts02": {
				"__ref": "content/Art/MaterialLibrary/Generic/Past.matlib",
				"name": "Wall_Joins"
			},
			"Wall_Idol": {
				"__ref": "content/Art/MaterialLibrary/Generic/Past.matlib",
				"name": "Wall_Idol"
			},
			"mosaique_plane": {
				"__ref": "content/Art/MaterialLibrary/Generic/Past.matlib",
				"name": "Wall_pattern04"
			},
			"debris": {
				"__ref": "content/Art/MaterialLibrary/Assets/Debris.matlib",
				"name": "Debris_Tileable"
			},
			"dalles_mesh": {
				"__ref": "content/Art/MaterialLibrary/Generic/Past.matlib",
				"name": "Wall_bricks02"
			},
			"Garden_ground": {
				"__ref": "content/Art/MaterialLibrary/Vegetation/Vegetation.matlib",
				"name": "Garden_ground"
			},
			"Moss": {
				"__ref": "content/Art/MaterialLibrary/Vegetation/Vegetation.matlib",
				"name": "Foliage_test"
			}
		}
	}
}