{
	"materials": {
		"Fatherlands": {
			"tree_forest": {
				"__ref": "content/Art/MaterialLibrary/Vegetation/Vegetation.matlib",
				"name": "Tree_Background"
			},
			"01 - Default": {
				"__ref": "content/Art/MaterialLibrary/Vegetation/Vegetation.matlib",
				"name": "Garden_ground",
				"colorMask": 15
			},
			"02 - Default": {
				"__ref": "content/Art/MaterialLibrary/Vegetation/Vegetation.matlib",
				"name": "Tree_Background"
			},
			"01 - Default/exterior_plane_pinetrees.fbx": {
				"__ref": "content/Art/MaterialLibrary/Vegetation/Vegetation.matlib",
				"name": "Tree_Background",
				"__refMode": "modelSpec"
			},
			"default/Ladder.fbx": {
				"__ref": "content/Art/MaterialLibrary/Generic/Utilities.matlib",
				"name": "BaseMetal",
				"__refMode": "modelSpec"
			},
			"default/exterior_plane.fbx": {
				"__ref": "content/Art/MaterialLibrary/Vegetation/Vegetation.matlib",
				"name": "green",
				"__refMode": "modelSpec"
			},
			"default/plane_test.fbx": {
				"__ref": "content/Art/MaterialLibrary/Generic/Past.matlib",
				"name": "Wall_Bloc",
				"__refMode": "modelSpec"
			},
			"default": {
				"mode": "PBR",
				"blend": "None",
				"shadows": true,
				"culling": "Back",
				"depthTest": "Less",
				"colorMask": 15,
				"enableStencil": false,
				"textureWrap": true,
				"parallax": 0
			}
		}
	}
}